github_url: https://github.com/indieSoftware/NavigationStack
author: Sven Korset
theme: fullwidth
title: NavigationStack
module: NavigationStack
clean: true
output: ./docs
readme: README.md
skip_undocumented: false
hide_documentation_coverage: false
min_acl: public
sdk: iphone
objc: false
swift_build_tool: xcodebuild
xcodebuild_arguments:
  - build
  - -workspace
  - NavigationStack.xcworkspace
  - -scheme
  - NavigationStack
custom_categories: 
  - name: NavigationStack
    children:
      - NavigationModel
      - NavigationStackView
      - NavigationAnimation
  - name: Transition Animations
    children:
      - AnyTransition
  - name: Modifier Structs
    children:
      - BlurModifier
      - BrightnessModifier
      - ClipShapeModifier
      - ContrastModifier
      - HueRotationModifier
      - SaturationModifier
  - name: Shapes usable by ClipShapeModifier
    children:
      - CircleShape
      - RectangleShape
      - StripesShape
