coverage_service: cobertura_xml
workspace: NavigationStack.xcworkspace
xcodeproj: NavigationStack.xcodeproj
scheme: NavigationStack
output_directory: reports
ignore:
  - NavigationStackExample/*
  - NavigationStackExampleUITests/*
  - NavigationStackTests/*
