language: swift
os: osx
osx_image: xcode12
xcode_workspace: NavigationStack.xcworkspace
cache: 
  bundler: true
  cocoapods: true
jobs:
  include:
    - name: Test Lib on iPhone 8 (13.0)
      xcode_scheme: NavigationStack
      xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 8
    - name: Test Lib on iPhone 11 (14.0) and upload code coverage
      xcode_scheme: NavigationStack
      xcode_destination: platform=iOS Simulator,OS=14.0,name=iPhone 11
      after_success:
        - bundle exec slather
        - bash <(curl -s https://codecov.io/bash) -f reports/cobertura.xml -X coveragepy -X gcov -X xcode
    - name: Test Example on iPhone 11 (14.0)
      xcode_scheme: NavigationStackExample
      xcode_destination: platform=iOS Simulator,OS=14.0,name=iPhone 11

branches:
  only:
    - master
